/**
 * "Take the swarm with you" exporters.
 *
 * Turns a finished run into a self-contained script you can run from a
 * terminal — the same goal, the same agent order, the same system prompts.
 * The generated code reads the key from the environment, never from the app.
 */
import { AGENTS, DEFAULT_MODEL } from "./constants.js";

const q = (value = "") => JSON.stringify(String(value));

const slug = (name = "agent") => String(name).toLowerCase().replace(/[^a-z0-9]+/g, "-");

/** Resolve the agents a script should reproduce, in order. */
function scriptAgents({ plan = [], goal = "" } = {}) {
  const steps = Array.isArray(plan) && plan.length ? plan : [{ name: "CODER", instruction: `Deliver the goal: ${goal}` }];
  return steps.map((step, index) => {
    const def = AGENTS[step.name] || {};
    return {
      name: step.name || `AGENT_${index + 1}`,
      instruction: step.instruction || step.name || "",
      system: def.sys || "You are a specialised agent in an AI swarm. Be concise, concrete and production-grade.",
    };
  });
}

/**
 * @param {object} run
 * @param {"node"|"python"|"curl"} run.format
 * @param {string} run.goal
 * @param {Array<{name: string, instruction: string}>} run.plan
 * @param {string} [run.model]
 * @param {number} [run.maxTokens]
 */
export function buildRunScript({ format = "node", goal = "", plan = [], model = DEFAULT_MODEL, maxTokens = 1600 } = {}) {
  const agents = scriptAgents({ plan, goal });
  if (format === "python") return pythonScript({ goal, agents, model, maxTokens });
  if (format === "curl") return curlScript({ goal, agents, model, maxTokens });
  return nodeScript({ goal, agents, model, maxTokens });
}

function nodeScript({ goal, agents, model, maxTokens }) {
  return `#!/usr/bin/env node
/**
 * Neural Swarm dispatch — generated by the studio.
 * Reproduces this run locally: ${agents.length} agent${agents.length === 1 ? "" : "s"}, sequential, chained context.
 *
 *   ANTHROPIC_API_KEY=<your key> node swarm-run.mjs
 */
const GOAL = ${q(goal)};
const MODEL = ${q(model)};
const MAX_TOKENS = ${maxTokens};

const AGENTS = ${JSON.stringify(agents, null, 2)};

const key = process.env.ANTHROPIC_API_KEY;
if (!key) {
  console.error("Set ANTHROPIC_API_KEY first (console.anthropic.com → API keys).");
  process.exit(1);
}

async function callAgent(agent, priorContext) {
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-api-key": key,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: MAX_TOKENS,
      system: agent.system,
      messages: [
        {
          role: "user",
          content: \`GOAL: \${GOAL}\\n\\nYOUR TASK: \${agent.instruction}\${priorContext ? \`\\n\\nPRIOR OUTPUT:\\n\${priorContext}\` : ""}\`,
        },
      ],
    }),
  });
  if (!res.ok) throw new Error(\`\${agent.name}: HTTP \${res.status} \${await res.text()}\`);
  const data = await res.json();
  return (data.content || []).map((part) => part.text || "").join("");
}

const context = [];
for (const agent of AGENTS) {
  process.stderr.write(\`▸ \${agent.name} …\\n\`);
  const text = await callAgent(agent, context.map((c) => \`[\${c.name}]\\n\${c.text}\`).join("\\n\\n"));
  context.push({ name: agent.name, text });
  console.log(\`\\n## \${agent.name}\\n\\n\${text}\`);
}
`;
}

function pythonScript({ goal, agents, model, maxTokens }) {
  return `#!/usr/bin/env python3
"""Neural Swarm dispatch — generated by the studio. No dependencies (urllib)."""
import json
import os
import urllib.request

GOAL = ${q(goal)}
MODEL = ${q(model)}
MAX_TOKENS = ${maxTokens}
AGENTS = json.loads(r'''${JSON.stringify(agents, null, 2)}''')

KEY = os.environ.get("ANTHROPIC_API_KEY")
if not KEY:
    raise SystemExit("Set ANTHROPIC_API_KEY first (console.anthropic.com -> API keys).")


def call_agent(agent, prior_context):
    payload = {
        "model": MODEL,
        "max_tokens": MAX_TOKENS,
        "system": agent["system"],
        "messages": [
            {
                "role": "user",
                "content": f"GOAL: {GOAL}\\n\\nYOUR TASK: {agent['instruction']}"
                + (f"\\n\\nPRIOR OUTPUT:\\n{prior_context}" if prior_context else ""),
            }
        ],
    }
    request = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=json.dumps(payload).encode(),
        headers={
            "content-type": "application/json",
            "x-api-key": KEY,
            "anthropic-version": "2023-06-01",
        },
    )
    with urllib.request.urlopen(request, timeout=120) as response:
        data = json.load(response)
    return "".join(part.get("text", "") for part in data.get("content", []))


context = []
for agent in AGENTS:
    print(f"▸ {agent['name']} …", flush=True)
    text = call_agent(agent, "\\n\\n".join(f"[{c['name']}]\\n{c['text']}" for c in context))
    context.append({"name": agent["name"], "text": text})
    print(f"\\n## {agent['name']}\\n\\n{text}")
`;
}

function curlScript({ goal, agents, model, maxTokens }) {
  const steps = agents
    .map((agent, index) => {
      const file = `${String(index + 1).padStart(2, "0")}-${slug(agent.name)}.md`;
      const body = {
        model,
        max_tokens: maxTokens,
        system: agent.system,
        messages: [{ role: "user", content: `GOAL: ${goal}\n\nYOUR TASK: ${agent.instruction}` }],
      };
      return `# ${agent.name}
cat > payload-${index + 1}.json <<'JSON'
${JSON.stringify(body, null, 2)}
JSON
curl -s https://api.anthropic.com/v1/messages \\
  -H "x-api-key: $ANTHROPIC_API_KEY" \\
  -H "anthropic-version: 2023-06-01" \\
  -H "content-type: application/json" \\
  -d @payload-${index + 1}.json | tee raw-${index + 1}.json | jq -r '.content[0].text' > ${file}
echo "wrote ${file}"`;
    })
    .join("\n\n");

  return `#!/usr/bin/env bash
# Neural Swarm dispatch — generated by the studio.
# Sequential and unchained: each agent answers independently (chain by pasting
# the previous file into the next payload if you need shared context).
set -euo pipefail

if [[ -z "\${ANTHROPIC_API_KEY:-}" ]]; then
  echo "Set ANTHROPIC_API_KEY first (console.anthropic.com -> API keys)." >&2
  exit 1
fi

${steps}
`;
}
