import { Octokit } from "@octokit/rest";
import { SwarmSDK } from "./src/swarm-logic.js";

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
const [owner, repo] = ["XxXKoZXxX", "neural-swarm"];
const DRY_RUN = process.argv.includes("--dry-run");

async function getFailedLogs(runId) {
  const { data: jobs } = await octokit.rest.actions.listJobsForWorkflowRun({
    owner, repo, run_id: runId,
  });

  const failed = jobs.jobs.filter(j => j.conclusion === "failure");
  const logs = [];

  for (const job of failed.slice(0, 3)) {
    try {
      const { data } = await octokit.rest.actions.downloadJobLogsForWorkflowRun({
        owner, repo, job_id: job.id,
      });
      const text = typeof data === "string" ? data : JSON.stringify(data);
      logs.push(`### Job: ${job.name}\n${text.slice(-4000)}`);
    } catch {
      logs.push(`### Job: ${job.name}\n[Logs unavailable — check run directly]`);
    }
  }

  return logs.join("\n\n");
}

async function createHealingIssue(run, diagnosis) {
  const { data: issue } = await octokit.rest.issues.create({
    owner, repo,
    title: `[SENTINEL] ${run.name} failed @ ${run.head_sha.slice(0, 7)} on ${run.head_branch}`,
    body: [
      `## Sentinel Auto-Diagnosis`,
      ``,
      `| Field | Value |`,
      `|-------|-------|`,
      `| Run | [${run.id}](${run.html_url}) |`,
      `| Commit | \`${run.head_sha}\` |`,
      `| Branch | \`${run.head_branch}\` |`,
      `| Triggered | ${run.event} |`,
      ``,
      `---`,
      ``,
      `## Debugger Analysis`,
      ``,
      diagnosis,
      ``,
      `---`,
      `*Auto-generated by Sentinel. Apply the fix above and re-run the workflow.*`,
    ].join("\n"),
    labels: ["sentinel", "ci-failure"],
  });
  return issue;
}

async function healPipeline() {
  console.log("[SENTINEL] Scanning for failures...");

  const { data: runs } = await octokit.rest.actions.listWorkflowRunsForRepo({
    owner, repo, status: "failure", per_page: 1,
  });

  if (!runs.workflow_runs.length) {
    console.log("[SENTINEL] ✓ System Nominal. No failures detected.");
    return;
  }

  const run = runs.workflow_runs[0];
  console.log(`[SENTINEL] Failed run: ${run.id} | "${run.name}" @ ${run.head_sha.slice(0, 7)} on ${run.head_branch}`);

  const errorLogs = await getFailedLogs(run.id);
  console.log("[SENTINEL] Logs extracted. Dispatching DEBUGGER agent...");

  const diagnosis = await SwarmSDK.triggerAgent("Debugger", {
    context: `CI/CD pipeline failure in ${owner}/${repo}.\nWorkflow: ${run.name}\nBranch: ${run.head_branch}\nCommit: ${run.head_sha}\nTriggered by: ${run.event}`,
    errorLogs,
    task: "Identify the root cause of this CI failure. Provide:\n1. Root cause (1-2 sentences)\n2. Exact fix with file path and code change\n3. Confidence level: HIGH / MEDIUM / LOW\n\nIf confidence is HIGH, format the fix as a fenced code block with the filename as the language tag.",
    personality: "Dark Detective",
  });

  console.log("\n[DEBUGGER OUTPUT]:\n");
  console.log(diagnosis);
  console.log();

  if (DRY_RUN) {
    console.log("[SENTINEL] --dry-run mode: skipping issue creation.");
    return;
  }

  const issue = await createHealingIssue(run, diagnosis);
  console.log(`[SENTINEL] ✓ Healing issue created: ${issue.html_url}`);
}

healPipeline().catch(err => {
  console.error("[SENTINEL] Fatal:", err.message);
  process.exit(1);
});
